package com.cbi_solar.helper

object ApiContants {

        const val PREF_base_url = "https://cbisolar.in/cbipanel/Api/Api/"
        const val PREF_ImageUrl = "https://cbisolar.in/cbipanel"
        const val PREF_customerlogin = "customerlogin"
        const val PREF_profile = "profile"
        const val PREF_customer_regis = "customer_regis"
        const val PREF_ser_req = "ser_req"
        const val PREF_profileupdate = "profileupdate"
        const val PREF_passwordchange = "passwordchange"
        const val PREF_StoreList = "store"
        const val PREF_notification = "notification"
        const val PREF_product_list = "product_list"
        const val PREF_banner_list = "banner_list"
        const val PREF_ser_req_status = "ser_req_status"
        const val PREF_winner_list = "winner_list"
        const val PREF_privacypolicy = "https://cbisolar.in/privacypolicy.html"

        const val PREF_UserAPI = "userAPI"
        const val PREF_ClinicAPI = "clinicAPI"
        const val PREF_new_prospect = "new_prospect"
        const val PREF_appointmentAPI = "appointmentAPI"

        const val id = "id"
        const val login = "login"

        const val PREF_city = "city"
        const val PREF_pin = "pin"
        const val PREF_providername = "providername"
        const val PREF_registration = "registration"
        const val PREF_error_message = "error_message"
        const val PREF_providerid = "providerid"
        const val PREF_longitude = "longitude"
        const val PREF_st = "st"
        const val PREF_cell = "cell"
        const val PREF_usertype = "usertype"
        const val PREF_practiceaddress = "practiceaddress"
        const val PREF_result = "result"
        const val PREF_provider = "provider"
        const val PREF_latitude = "latitude"
        const val PREF_practicename = "practicename"
        const val PREF_locationurl = "locationurl"
        const val PREF_error_code = "error_code"
        const val PREF_email = "email"

        const val PREF_IsLogin = "PREF_IsLogin"
        const val PREF_ref_code = "PREF_ref_code"
        const val PREF_clinic_count = "PREF_clinic_count"
        const val PREF_ref_id = "PREF_ref_id"
        const val PREF_prospectid = "PREF_prospectid"
        const val PREF_totaldownline = "PREF_totaldownline"
        const val PREF_AMOUNT = "Loan_amount"
        const val PREF_totaldirect = "totaldirect"
        const val status1 = "status1"
        const val PREF_device = "PREF_device"
        const val PREF_Address = "PREF_Address"
        const val PREF_Balance = "PREF_Balance"
        const val PREF_operator_code = "PERF_Operoto_code"
        const val PREF_amt = "PREF_amt"
        const val PREF_temp_number = "PREF_temp_number"
        const val PREF_Landmark = "PREF_Landmark"
        const val PREF_CountryCode = "PREF_CountryCode"
        const val PREF_StateId = "PREF_StateId"
        const val PREF_Zip = "PREF_Zip"
        const val PREF_GST_no = "PREF_GST_no"
        const val PREF_F_name = "PREF_F_name"
        const val PREF_L_name = "PREF_L_name"
        const val WhatsAppNumber = "PREF_L_name"
}